export const GET_CART = 'GET_CART'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const LOAD_CART_DATA = 'LOAD_CART_DATA'

export const GET_CATEGORIES = 'GET_CATEGORIES'
export const CATEGORIES_LOADING = 'CATEGORIES_LOADING'

export const GET_PRODUCTS = 'GET_PRODUCTS'