export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const LOAD_CART_DATA = 'LOAD_CART_DATA'
export const CART_LOADING = 'CART_LOADING'
export const CART_ERRORED = 'CART_ERRORED'

export const GET_CATEGORIES = 'GET_CATEGORIES'
export const CATEGORIES_LOADING = 'CATEGORIES_LOADING'
export const CATEGORIES_ERRORED = 'CATEGORIES_ERRORED'

export const GET_PRODUCTS = 'GET_PRODUCTS'
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING'
export const PRODUCTS_ERRORED = 'PRODUCTS_ERRORED'

export const GET_PRODUCT_INFO = 'GET_PRODUCT_INFO'
export const PRODUCT_LOADING = 'PRODUCT_LOADING'
export const PRODUCT_ERRORED = 'PRODUCT_ERRORED'